### ISSUE TITLE
Allow Users To View Only Their Calendar

### ISSUE THREAD

**Issue by ScottDeLuzio** [mpeshev/wp-crm-system#24]
# Feature Request

## User Story

As a user, I want to only view information on the Dashboard calendar that I am assigned to so that I do not have to click through each entry to see if it is one of my projects/tasks/etc.

There should be an option to view all as well (the current view users are used to seeing), and an option to see other users calendars. The ability to view other users calendars should be disabled if View Other User Content is disabled in the main plugin settings.

## Possible Solution

Create a select menu that picks users who have access to WP-CRM System. Once selected, the calendar should only show that user's entries.

The select menu should save the selection to the current user's meta so that when that individual user returns to the dashboard, they still see the same calendar as the last time they viewed it. This way each user can set it to the view they want to see and expect to continue seeing it each time the view the calendar without having to reset their view every time.

By default, if no selection is made the calendar should show all entries as it currently does.

## Related

https://secure.helpscout.net/conversation/1035085200/6800?folderId=996664
## Acceptance Criteria

- [ ] A select menu of users should be available near the calendar on the dashboard.
- [ ] When a user is selected, the selection should be saved to the current user's meta. 
- [ ] Future visits to the dashboard should check for this selection so the user doesn't have to constantly update the dashboard view every time they come back to it.
- [ ] The default view should be viewing all records on the calendar as that is the current default view. We do not want to change the default on anyone without them expecting it to change by making the selection themselves.
